/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

module derelict.sass.functions;

private {
    import derelict.sass.options;
    import derelict.util.system;
}

extern( C ) @nogc nothrow {
    alias da_sass_new_context = sass_context* function();
    alias da_sass_new_file_context = sass_file_context* function();
    alias da_sass_new_folder_context = sass_folder_context* function();

    alias da_sass_free_context = void function( sass_context* ctx );
    alias da_sass_free_file_context = void function( sass_file_context* ctx );
    alias da_sass_free_folder_context = void function( sass_folder_context* ctx );

    alias da_sass_compile = int function( sass_context* ctx );
    alias da_sass_compile_file = int function( sass_file_context* ctx );
    alias da_sass_compile_folder = int function( sass_folder_context* ctx );

    alias da_sass2scss = char* function( const(char)* sass, const(int) options );

    alias da_sass_string_quote =  char* function( const(char)* str, const(char) quotemark );
    alias da_sass_string_unquote = char* function( const(char)* str );
}

__gshared {
    da_sass_new_context sass_new_context;
    da_sass_new_file_context sass_new_file_context;
    da_sass_new_folder_context sass_new_folder_context;

    da_sass_free_context sass_free_context;
    da_sass_free_file_context sass_free_file_context;
    da_sass_free_folder_context sass_free_folder_context;

    da_sass_compile sass_compile;
    da_sass_compile_file sass_compile_file;
    da_sass_compile_folder sass_compile_folder;

    da_sass2scss sass2scss;
    da_sass_string_quote sass_string_quote;
    da_sass_string_unquote sass_string_unquote;
}