/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

module derelict.sass.options;

private{
    import derelict.sass.types;
}

enum {
    SASS_STYLE_NESTED,
    SASS_STYLE_EXPANDED,
    SASS_STYLE_COMPACT,
    SASS_STYLE_COMPRESSED
}

enum {
    SASS2SCSS_PRETTIFY_0 = 0,
    SASS2SCSS_PRETTIFY_1 = 1,
    SASS2SCSS_PRETTIFY_2 = 2,
    SASS2SCSS_PRETTIFY_3 = 3,
    
    SASS2SCSS_KEEP_COMMENT = 32,
    SASS2SCSS_STRIP_COMMENT = 64,
    SASS2SCSS_CONVERT_COMMENT = 128,
}

struct sass_options {
    int output_style;
    bool source_comments;
    const(char)* source_map_file;
    bool omit_source_map_url;
    bool source_map_embed;
    bool source_map_contents;
    bool is_indented_syntax_src;
    const(char)* include_paths;
    const(char)* image_path;
    int precision;
}

struct sass_context {
    const(char)* input_path;
    const(char)* output_path;
    const(char)* source_string;
    char* output_string;
    char* source_map_string;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}

struct sass_file_context {
    const(char)* input_path;
    const(char)* output_path;
    char* output_string;
    char* source_map_string;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}

struct sass_folder_context {
    const(char)* search_path;
    const(char)* output_path;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}