/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

module derelict.sass.sass;

private {
    import derelict.util.loader;
    import derelict.util.exception;
    import derelict.util.system;

    static if( Derelict_OS_Windows ) {
        enum libNames = "libsass.dll";
    } else static if( Derelict_OS_Posix ) {
        enum libNames = "libsass.so,/usr/local/lib/libsass.so";
    } else {
        static assert( 0, "Need to implement libsass libNames for this operating system." );
    }
}

enum {
    SASS_STYLE_NESTED = 0,
    SASS_STYLE_EXPANDED = 1,
    SASS_STYLE_COMPACT = 2,
    SASS_STYLE_COMPRESSED = 3,

    SASS2SCSS_PRETTIFY_0 = 0,
    SASS2SCSS_PRETTIFY_1 = 1,
    SASS2SCSS_PRETTIFY_2 = 2,
    SASS2SCSS_PRETTIFY_3 = 3,
    
    SASS2SCSS_KEEP_COMMENT = 32,
    SASS2SCSS_STRIP_COMMENT = 64,
    SASS2SCSS_CONVERT_COMMENT = 128,
}

alias Sass_Tag = int;
enum : Sass_Tag {
    SASS_BOOLEAN,
    SASS_NUMBER,
    SASS_COLOR,
    SASS_STRING,
    SASS_LIST,
    SASS_MAP,
    SASS_NULL,
    SASS_ERROR
}

alias Sass_Separator = int;
enum : Sass_Separator {
    SASS_COMMA,
    SASS_SPACE
}

struct sass_options {
    int output_style;
    bool source_comments;
    const(char)* source_map_file;
    bool omit_source_map_url;
    bool source_map_embed;
    bool source_map_contents;
    bool is_indented_syntax_src;
    const(char)* include_paths;
    const(char)* image_path;
    int precision;
}

struct sass_context {
    const(char)* input_path;
    const(char)* output_path;
    const(char)* source_string;
    char* output_string;
    char* source_map_string;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}

struct sass_file_context {
    const(char)* input_path;
    const(char)* output_path;
    char* output_string;
    char* source_map_string;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}

struct sass_folder_context {
    const(char)* search_path;
    const(char)* output_path;
    sass_options options;
    int error_status;
    char* error_message;
    Sass_C_Function_List c_functions;
    char** included_files;
    int num_included_files;
}

struct Sass_C_Function_Descriptor {
    const(char)* signature;
    Sass_C_Function function_;
    void* cookie;
}

union Sass_Value {
    Sass_Unknown unknown;
    Sass_Boolean boolean;
    Sass_Number number;
    Sass_Color color;
    Sass_String string;
    Sass_List list;
    Sass_Map map;
    Sass_Null null_;
    Sass_Error error;
}

struct Sass_Unknown {
    Sass_Tag tag;
}

struct Sass_Boolean {
    Sass_Tag tag;
    bool value;
}

struct Sass_Number {
    Sass_Tag tag;
    double value;
    char* unit;
}

struct Sass_Color {
    Sass_Tag tag;
    double r;
    double g;
    double b;
    double a;
}

struct Sass_String {
    Sass_Tag tag;
    char* value;
}

struct Sass_List {
    Sass_Tag tag;
    Sass_Separator separator;
    size_t length;
    Sass_Value** values;
}

struct Sass_Map {
    Sass_Tag tag;
    size_t length;
    Sass_MapPair* pairs;
}

struct Sass_Null {
    Sass_Tag tag;
}

struct Sass_Error {
    Sass_Tag tag;
    char* message;
}

struct Sass_MapPair {
    Sass_Value* key;
    Sass_Value* value;
}

extern( C ) @nogc nothrow {
    alias Sass_C_Function_List = Sass_C_Function_Descriptor* function ();
    alias Sass_C_Function = Sass_Value* function (Sass_Value*, void* cookie);
}

extern( C ) @nogc nothrow {
    alias da_sass_new_context = sass_context* function();
    alias da_sass_new_file_context = sass_file_context* function();
    alias da_sass_new_folder_context = sass_folder_context* function();
    
    alias da_sass_free_context = void function( sass_context* ctx );
    alias da_sass_free_file_context = void function( sass_file_context* ctx );
    alias da_sass_free_folder_context = void function( sass_folder_context* ctx );
    
    alias da_sass_compile = int function( sass_context* ctx );
    alias da_sass_compile_file = int function( sass_file_context* ctx );
    alias da_sass_compile_folder = int function( sass_folder_context* ctx );
    
    alias da_sass2scss = char* function( const(char)* sass, const(int) options );
    
    alias da_sass_string_quote =  char* function( const(char)* str, const(char) quotemark );
    alias da_sass_string_unquote = char* function( const(char)* str );
}

__gshared {
    da_sass_new_context sass_new_context;
    da_sass_new_file_context sass_new_file_context;
    da_sass_new_folder_context sass_new_folder_context;
    
    da_sass_free_context sass_free_context;
    da_sass_free_file_context sass_free_file_context;
    da_sass_free_folder_context sass_free_folder_context;
    
    da_sass_compile sass_compile;
    da_sass_compile_file sass_compile_file;
    da_sass_compile_folder sass_compile_folder;
    
    da_sass2scss sass2scss;
    da_sass_string_quote sass_string_quote;
    da_sass_string_unquote sass_string_unquote;
}

class DerelictSassLoader : SharedLibLoader {
    public this() {
        super( libNames );
    }
    
    protected override void loadSymbols() {
        bindFunc( cast( void** )&sass_new_context, "sass_new_context" );
        bindFunc( cast( void** )&sass_new_file_context, "sass_new_file_context" );
        bindFunc( cast( void** )&sass_new_folder_context, "sass_new_folder_context" );
        bindFunc( cast( void** )&sass_free_context, "sass_free_context" );
        bindFunc( cast( void** )&sass_free_file_context, "sass_free_file_context" );
        bindFunc( cast( void** )&sass_free_folder_context, "sass_free_folder_context" );
        bindFunc( cast( void** )&sass_compile, "sass_compile" );
        bindFunc( cast( void** )&sass_compile_file, "sass_compile_file" );
        bindFunc( cast( void** )&sass_compile_folder, "sass_compile_folder" );
        bindFunc( cast( void** )&sass2scss, "sass2scss" );
        bindFunc( cast( void** )&sass_string_quote, "sass_string_quote" );
        bindFunc( cast( void** )&sass_string_unquote, "sass_string_unquote" );
    }
}

__gshared DerelictSassLoader DerelictSass;

shared static this() {
    DerelictSass = new DerelictSassLoader;
}